# packages in environment at /Users/virgil/anaconda3/envs/metr:
#
# Name                    Version                   Build  Channel
affine                    2.3.0                      py_0  
aiohttp                   3.7.3            py38h5406a74_1    conda-forge
appdirs                   1.4.3                      py_1    conda-forge
appnope                   0.1.0           py38h32f6830_1001    conda-forge
argon2-cffi               20.1.0           py38h4d0b108_1    conda-forge
arm_pyart                 1.11.2           py38h174b24a_0    conda-forge
astropy                   4.0.2            py38haf1e3a3_0  
async-timeout             3.0.1                   py_1000    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     20.2.0             pyh9f0ad1d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
basemap                   1.2.2            py38hcfa07f7_0    conda-forge
beautifulsoup4            4.9.3              pyhb0f4dca_0    conda-forge
bleach                    3.2.1              pyh9f0ad1d_0    conda-forge
bokeh                     2.2.1            py38h32f6830_0    conda-forge
boost-cpp                 1.74.0               he5d75e3_0    conda-forge
brotlipy                  0.7.0           py38h4d0b108_1000    conda-forge
bzip2                     1.0.8                haf1e3a3_3    conda-forge
c-ares                    1.16.1               haf1e3a3_3    conda-forge
ca-certificates           2021.4.13            hecd8cb5_1  
cairo                     1.16.0            ha8983da_1005    conda-forge
cartopy                   0.18.0           py38h54cc3bc_2    conda-forge
cdsapi                    0.5.1                    pypi_0    pypi
certifi                   2020.12.5        py38hecd8cb5_0  
cffi                      1.14.3           py38hc4dd44e_0    conda-forge
cfgrib                    0.9.8.4                    py_0    conda-forge
cfitsio                   3.470                hdf94aef_6    conda-forge
cftime                    1.2.1            py38h9c4ca6c_0    conda-forge
chardet                   3.0.4           py38h32f6830_1007    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.1              pyhd8ed1ab_0    conda-forge
cloudpickle               1.6.0                      py_0    conda-forge
cryptography              3.1.1            py38h52adbb4_0    conda-forge
curl                      7.71.1               hcb81553_8    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cytoolz                   0.11.0           py38h4d0b108_0    conda-forge
dask                      2.28.0                     py_0    conda-forge
dask-core                 2.28.0                     py_0    conda-forge
dbus                      1.13.6               h2f22bb5_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
distributed               2.30.0           py38h32f6830_0    conda-forge
eccodes                   2.18.0               h031fe05_0    conda-forge
entrypoints               0.3             py38h32f6830_1001    conda-forge
expat                     2.2.9                hb1e8313_2    conda-forge
fake-useragent            0.1.11                   pypi_0    pypi
ffmpeg                    4.3.1                h9903f1f_0    conda-forge
fiona                     1.8.17           py38hcfd527e_0    conda-forge
fontconfig                2.13.1            h79c0d67_1002    conda-forge
freetype                  2.10.2               h8da9a1a_0    conda-forge
freexl                    1.0.5             h0b31af3_1002    conda-forge
fsspec                    0.8.3                      py_0    conda-forge
gdal                      3.1.2            py38hbe58a21_1    conda-forge
geopandas                 0.8.2              pyhd8ed1ab_0    conda-forge
geos                      3.8.1                h4a8c4bd_0    conda-forge
geotiff                   1.6.0                h4e9c399_1    conda-forge
gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
giflib                    5.2.1                h0b31af3_2    conda-forge
glib                      2.66.1               h39b9ebd_0    conda-forge
gmp                       6.2.0                hb1e8313_2    conda-forge
gnutls                    3.6.13               hc269f14_0    conda-forge
h5netcdf                  0.8.1                      py_0    conda-forge
h5py                      2.10.0          nompi_py38hf6831e1_105    conda-forge
hdf4                      4.2.13            h84186c3_1003    conda-forge
hdf5                      1.10.6          nompi_haae91d6_101    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
icu                       67.1                 hb1e8313_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
importlib-metadata        2.0.0            py38h32f6830_0    conda-forge
importlib_metadata        2.0.0                         0    conda-forge
importlib_resources       3.0.0            py38h32f6830_0    conda-forge
ipykernel                 5.3.4            py38h23f93f0_0    conda-forge
ipython                   7.18.1           py38h1cdfbd6_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1              pyh9f0ad1d_1    conda-forge
jasper                    1.900.1           h636a363_1006    conda-forge
jedi                      0.15.2                   py38_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
joblib                    1.0.1              pyhd3eb1b0_0  
jpeg                      9d                   h0b31af3_0    conda-forge
json-c                    0.13.1            h575e443_1002    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonschema                3.2.0            py38h32f6830_1    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter-server-proxy      1.5.3              pyhd8ed1ab_0    conda-forge
jupyter_client            6.1.7                      py_0    conda-forge
jupyter_console           6.2.0                      py_0    conda-forge
jupyter_core              4.6.3            py38h32f6830_1    conda-forge
jupyterlab                2.2.6                      py_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         1.2.0                      py_0    conda-forge
kealib                    1.4.13               h40102fb_1    conda-forge
kiwisolver                1.2.0            py38ha0d09dd_0    conda-forge
krb5                      1.17.1               h75d18d8_3    conda-forge
lame                      3.100             h1de35cc_1001    conda-forge
lcms2                     2.11                 h174193d_0    conda-forge
libaec                    1.0.4                h4a8c4bd_1    conda-forge
libblas                   3.8.0               17_openblas    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
libclang                  10.0.1          default_hf57f61e_1    conda-forge
libcurl                   7.71.1               h9bf37e3_8    conda-forge
libcxx                    10.0.1               h5f48129_0    conda-forge
libdap4                   3.20.6               h993cace_1    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.2.1             hb1e8313_1007    conda-forge
libgdal                   3.1.2                h6dfbaa8_1    conda-forge
libgfortran               4.0.0               h2d743fc_11    conda-forge
libgfortran4              7.5.0               h2d743fc_11    conda-forge
libiconv                  1.16                 haf1e3a3_0    conda-forge
libkml                    1.3.0             h8ca2c65_1012    conda-forge
liblapack                 3.8.0               17_openblas    conda-forge
libllvm10                 10.0.1               h009f743_3    conda-forge
libnetcdf                 4.7.4           nompi_hc5b2cf3_105    conda-forge
libnghttp2                1.41.0               h7580e61_2    conda-forge
libopenblas               0.3.10          openmp_h63d9170_4    conda-forge
libpng                    1.6.37               hb0a8c7a_2    conda-forge
libpq                     12.3                 h489d428_0    conda-forge
libprotobuf               3.13.0               hab81aa3_0    conda-forge
libsodium                 1.0.18               haf1e3a3_1    conda-forge
libspatialindex           1.9.3                h4a8c4bd_3    conda-forge
libspatialite             4.3.0a            h231dce8_1039    conda-forge
libssh2                   1.9.0                h8a08a2b_5    conda-forge
libtiff                   4.1.0                h2ae36a8_6    conda-forge
libuv                     1.39.0               haf1e3a3_0    conda-forge
libwebp-base              1.1.0                h0b31af3_3    conda-forge
libxml2                   2.9.10               h2c6e4a5_2    conda-forge
llvm-openmp               10.0.1               h28b9765_0    conda-forge
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.9.2                hb1e8313_3    conda-forge
markupsafe                1.1.1            py38h4d0b108_1    conda-forge
matplotlib                3.3.1                         1    conda-forge
matplotlib-base           3.3.1            py38haed9462_1    conda-forge
metpy                     0.12.2                     py_0    conda-forge
mistune                   0.8.4           py38h64e0658_1001    conda-forge
msgpack-python            1.0.0            py38ha0d09dd_1    conda-forge
multidict                 5.1.0            py38h5406a74_1    conda-forge
munch                     2.5.0                      py_0    conda-forge
mysql-common              8.0.21                        2    conda-forge
mysql-libs                8.0.21               hfb8f7af_2    conda-forge
nbclient                  0.5.0                      py_0    conda-forge
nbconvert                 6.0.7            py38h32f6830_0    conda-forge
nbformat                  5.0.7                      py_0    conda-forge
ncurses                   6.2                  hb1e8313_1    conda-forge
nest-asyncio              1.4.1                      py_0    conda-forge
netcdf4                   1.5.4           nompi_py38he235a2f_102    conda-forge
nettle                    3.4.1             h3efe00b_1002    conda-forge
nodejs                    14.12.0              hdde0ff8_0    conda-forge
notebook                  6.1.4            py38h32f6830_0    conda-forge
nspr                      4.20              h0a44026_1000    conda-forge
nss                       3.47                 hc0980d9_0    conda-forge
numpy                     1.19.1           py38h8ccc501_2    conda-forge
olefile                   0.46                       py_0    conda-forge
openh264                  2.1.1                hd174df1_0    conda-forge
openjpeg                  2.3.1                h254dc36_3    conda-forge
openssl                   1.1.1k               h9ed2024_0  
owslib                    0.20.0                     py_0    conda-forge
packaging                 20.4               pyh9f0ad1d_0    conda-forge
pandas                    1.1.3            py38h11c0d25_0    conda-forge
pandoc                    2.10.1               haf1e3a3_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.5.2                      py_0    conda-forge
partd                     1.1.0                      py_0    conda-forge
patsy                     0.5.1                    py38_0  
pcre                      8.44                 h4a8c4bd_0    conda-forge
pexpect                   4.8.0            py38h32f6830_1    conda-forge
pickleshare               0.7.5           py38h32f6830_1001    conda-forge
pillow                    7.2.0            py38h83dc5e5_1    conda-forge
pint                      0.16.1                     py_0    conda-forge
pip                       20.2.3                     py_0    conda-forge
pixman                    0.38.0            h01d97ff_1003    conda-forge
pooch                     1.2.0                      py_0    conda-forge
poppler                   0.89.0               h3232a60_1    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                12.3                 h62ab893_0    conda-forge
proj                      7.1.0                h45baca5_1    conda-forge
prometheus_client         0.8.0              pyh9f0ad1d_0    conda-forge
prompt-toolkit            3.0.7                      py_0    conda-forge
prompt_toolkit            3.0.7                         0    conda-forge
protobuf                  3.13.0           py38h11c0d25_0    conda-forge
psutil                    5.7.2            py38h4d0b108_0    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyepsg                    0.4.0                      py_0    conda-forge
pyflakes                  2.2.0                    pypi_0    pypi
pygments                  2.7.1                      py_0    conda-forge
pygrib                    2.0.5            py38h24c4ddc_0    conda-forge
pymysql                   0.10.1                   pypi_0    pypi
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyproj                    2.6.1.post1      py38hf032eb0_1    conda-forge
pyqt                      5.12.3           py38hf180056_3    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtchart                 5.12                     pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.17.3           py38h4d0b108_0    conda-forge
pyshp                     2.1.2              pyh9f0ad1d_0    conda-forge
pysocks                   1.7.1            py38h32f6830_1    conda-forge
python                    3.8.5           h0ed32c4_9_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pyyaml                    5.3.1            py38h4d0b108_0    conda-forge
pyzmq                     19.0.2           py38h2c785a9_1    conda-forge
qt                        5.12.9               h717870c_0    conda-forge
qtconsole                 4.7.7              pyh9f0ad1d_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
rasterio                  1.1.7            py38hcfd527e_0    conda-forge
readline                  8.0                  h0678c8f_2    conda-forge
regionmask                0.6.2              pyhd8ed1ab_0    conda-forge
requests                  2.24.0             pyh9f0ad1d_0    conda-forge
rtree                     0.9.7            py38hc59ffc2_1    conda-forge
scikit-learn              0.23.2           py38hfde8033_0    conda-forge
scipy                     1.5.2            py38h1402333_0    conda-forge
seaborn                   0.11.1             pyhd3eb1b0_0  
send2trash                1.5.0                      py_0    conda-forge
setuptools                49.6.0           py38h32f6830_1    conda-forge
shapely                   1.7.1            py38h8918236_0    conda-forge
simpervisor               0.4                pyhd8ed1ab_0    conda-forge
siphon                    0.8.0           py38h32f6830_1003    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
snuggs                    1.4.7                      py_0  
sortedcontainers          2.2.2              pyh9f0ad1d_0    conda-forge
soupsieve                 2.0.1                      py_1    conda-forge
sqlite                    3.33.0               h960bd1c_0    conda-forge
statsmodels               0.12.2           py38ha1b04c9_0    conda-forge
tbb                       2019.9               ha1b3eb9_1    conda-forge
tblib                     1.6.0                      py_0    conda-forge
terminado                 0.9.1            py38h32f6830_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0  
tiledb                    2.0.8                h8973ade_1    conda-forge
tk                        8.6.10               hb0a8c7a_0    conda-forge
toolz                     0.11.1                     py_0    conda-forge
tornado                   6.0.4            py38h64e0658_1    conda-forge
tqdm                      4.58.0                   pypi_0    pypi
traitlets                 5.0.4                      py_1    conda-forge
trmm_rsl                  1.49                          3    conda-forge
typing-extensions         3.7.4.3                       0    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
tzcode                    2020a                h0b31af3_0    conda-forge
urllib3                   1.25.10                    py_0    conda-forge
useragent                 0.1.1                    pypi_0    pypi
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
widgetsnbextension        3.5.1            py38h32f6830_1    conda-forge
x264                      1!152.20180806       h1de35cc_0    conda-forge
xarray                    0.16.1                     py_0    conda-forge
xerces-c                  3.2.3                h0a0444a_1    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
yaml                      0.2.5                haf1e3a3_0    conda-forge
yarl                      1.6.3            py38h5406a74_1    conda-forge
zeromq                    4.3.3                hb1e8313_2    conda-forge
zict                      2.0.0                      py_0    conda-forge
zipp                      3.3.0                      py_0    conda-forge
zlib                      1.2.11            h7795811_1009    conda-forge
zstd                      1.4.5                h289c70a_2    conda-forge
